PHP_METHOD(CairoPath, __construct);
ZEND_BEGIN_ARG_INFO_EX(CairoPath____construct_args, ZEND_SEND_BY_VAL, ZEND_RETURN_VALUE, 0)
ZEND_END_ARG_INFO()

PHP_METHOD(CairoPath, toStr);
ZEND_BEGIN_ARG_INFO_EX(CairoPath__to_str_args, ZEND_SEND_BY_VAL, ZEND_RETURN_VALUE, 0)
ZEND_END_ARG_INFO()
